version: '3.3'

volumes:
  vendor:
    driver: local
  storage:
    driver: local
  bootstrap-cache:
    driver: local

services:

  backend:
    env_file:
      - .envs/apache.env
      - .envs/php-ini.env
      - .envs/app.env
    ports:
      - ${APPLICATION_RUNNING_PORT}:80
      - ${APPLICATION_RUNNING_HTTPS_PORT}:443
    volumes:
      - ../:/var/www/html
      - vendor:/var/www/html/vendor/
      - storage:/var/www/html/storage/
      - bootstrap-cache:/var/www/html/bootstrap/cache
